### GET request to example server
POST http://localhost:1337/locations
Content-Type: application/json

{
  "name": "Cat Spit",
  "phone": "555-1212",
  "note": "Hypertheory World Headquarters",
  "address": {
    "street": "118 S. Marginal",
    "city": "Cleveland",
    "state": "OH",
    "zip": "44703"
  }
}

###

GET http://localhost:1337/locations