### Link to the Admin Response
GET http://localhost:8080/__admin

### See The Mappings
GET http://localhost:8080/__admin/mappings

### Reset  (reload mappings, files, etc.)
POST http://localhost:8080/__admin/reset

### Requests  (See the requests that have been  received - useful for debugging)
GET http://localhost:8080/__admin/requests
